apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-labeler
  namespace: node-labeler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-labeler
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
