---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labeler
  namespace: node-labeler
  labels:
    app.kubernetes.io/name: node-labeler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labeler
  labels:
    app.kubernetes.io/name: node-labeler
rules:
  # Nodes — need patch for labeling
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  # Events
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  # Leader election
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-labeler
  labels:
    app.kubernetes.io/name: node-labeler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labeler
subjects:
  - kind: ServiceAccount
    name: node-labeler
    namespace: node-labeler
