apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: Exists
  endpoints:
    - port: http-metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          action: keep
          regex: argocd-.*-metrics
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: component
          regex: argocd-(.*)-metrics
          replacement: $1
