apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - gitlab
  selector:
    matchLabels:
      app: gitlab-exporter
  endpoints:
    - port: http-metrics
