apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: harbor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - harbor
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["harbor"]
  endpoints:
    - port: http-metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_name]
          action: keep
          regex: harbor-(core|registry|exporter)
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: component
          regex: harbor-(.*)
          replacement: $1
