apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mattermost
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - mattermost
  selector:
    matchLabels:
      app: mattermost-metrics
  endpoints:
    - port: metrics
