extends: default

rules:
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: whatever

ignore:
  - services/monitoring-stack/grafana/configmap-dashboard-*.yaml
  - services/monitoring-stack/prometheus/configmap.yaml
