apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: "CHANGEME_KC_ADMIN_PASSWORD"
  KC_BOOTSTRAP_ADMIN_CLIENT_ID: admin-cli-bootstrap
  KC_BOOTSTRAP_ADMIN_CLIENT_SECRET: CHANGEME_BOOTSTRAP_CLIENT_SECRET
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: CHANGEME_KEYCLOAK_DB_PASSWORD
