# DEPRECATED: Replaced by ForwardAuth (oauth2-proxy + Keycloak). Kept for rollback.
apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-users
  namespace: kube-system
type: Opaque
stringData:
  # CHANGEME: Generate with: htpasswd -nbB admin <password>
  users: "admin:CHANGEME_GENERATE_WITH_HTPASSWD"
