# OpsTree Redis Operator — RedisReplication CRD for Harbor
# Provides: 3-replica Redis replication (1 master + 2 replicas)
# Requires: redis-operator in redis-operator-system namespace
#
# Naming: CRD name "harbor-redis" → operator creates:
#   StatefulSet: harbor-redis        Pods: harbor-redis-{0,1,2}
#   Service:     harbor-redis        Headless: harbor-redis-headless
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: harbor-redis
  namespace: harbor
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    redisSecret:
      name: harbor-valkey-credentials
      key: password
  redisExporter:
    enabled: true
    image: oliver006/redis_exporter:latest
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: harvester
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  nodeSelector:
    workload-type: database
  podSecurityContext:
    runAsUser: 999
    fsGroup: 999
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: harbor-redis
            topologyKey: kubernetes.io/hostname
