apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mattermost-minio
  namespace: mattermost
spec:
  serviceName: mattermost-minio
  replicas: 1
  selector:
    matchLabels:
      app: mattermost-minio
  template:
    metadata:
      labels:
        app: mattermost-minio
    spec:
      nodeSelector:
        workload-type: general
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - name: minio
          image: docker.io/minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - name: s3
              containerPort: 9000
            - name: console
              containerPort: 9001
          envFrom:
            - secretRef:
                name: mattermost-minio-secret
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 2Gi
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: harvester
        resources:
          requests:
            storage: 20Gi
