# Test job templates

.test:go:
  stage: test
  image: golang:1.23-alpine
  variables:
    CGO_ENABLED: "0"
  script:
    - go test -v -race -coverprofile=coverage.out ./...
    - go tool cover -func=coverage.out
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.out
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+)%/'

.test:node:
  stage: test
  image: node:22-alpine
  script:
    - npm ci --prefer-offline
    - npm test
  artifacts:
    reports:
      junit: junit.xml
  rules:
    - exists:
        - package.json

.test:python:
  stage: test
  image: python:3.12-slim
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=junit.xml --cov --cov-report=xml
  artifacts:
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
