apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: dhi-manifest-watcher
  namespace: argocd
  labels:
    app.kubernetes.io/name: dhi-builder
spec:
  resource:
    dhi-manifest:
      namespace: dhi-builder
      group: ""
      version: v1
      resource: configmaps
      eventTypes:
        - ADD
        - UPDATE
      filter:
        labels:
          - key: app.kubernetes.io/name
            operation: "="
            value: dhi-builder
