apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: argo-rollouts
spec:
  args:
    - name: service-name
    - name: namespace
      value: default
    - name: threshold
      value: "0.98"
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= asFloat(args.threshold)
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_requests_total{service="{{args.service-name}}",namespace="{{args.namespace}}",code=~"2.."}[2m]))
            /
            sum(rate(http_requests_total{service="{{args.service-name}}",namespace="{{args.namespace}}"}[2m]))
