apiVersion: v1
kind: Secret
metadata:
  name: librenms-mariadb-credentials
  namespace: librenms
type: Opaque
stringData:
  password: CHANGEME_LIBRENMS_DB_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: librenms-mariadb-root
  namespace: librenms
type: Opaque
stringData:
  password: CHANGEME_LIBRENMS_DB_PASSWORD
