apiVersion: v1
kind: Secret
metadata:
  name: mattermost-secret
  namespace: mattermost
type: Opaque
stringData:
  MM_SQLSETTINGS_DATASOURCE: "postgres://mattermost:CHANGEME_MATTERMOST_DB_PASSWORD@mattermost-pg-rw.database.svc.cluster.local:5432/mattermost?sslmode=disable&connect_timeout=10"
  MM_FILESETTINGS_AMAZONS3ACCESSKEYID: CHANGEME_MINIO_ROOT_USER
  MM_FILESETTINGS_AMAZONS3SECRETACCESSKEY: CHANGEME_MINIO_ROOT_PASSWORD
