apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: identity-portal-backend
  namespace: identity-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity-portal-backend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
