# =============================================================================
# Sample ArgoCD Application that manages a Rollout-based deployment
# =============================================================================
# This Application watches a Git repo path and syncs Rollout + Services.
# Argo Rollouts takes over the actual deployment strategy (blue/green or canary).
# ArgoCD health checks understand Rollout CRDs natively when Argo Rollouts is installed.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:derhornspieler/sample-app.git
    targetRevision: main
    path: deploy/production
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    # Argo Rollouts manages replica count during progressive delivery
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
