apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-core
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: harbor-core
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
