apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: harbor-trivy
  namespace: harbor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: harbor-trivy
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
