# DEPRECATED: Replaced by ForwardAuth (oauth2-proxy + Keycloak). Kept for rollback.
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
  namespace: argo-rollouts
spec:
  basicAuth:
    secret: basic-auth-users
