# CloudNativePG Cluster for Harbor
# Requires: CNPG operator in cnpg-system namespace (already deployed)
# Creates: 3-instance PostgreSQL cluster with 'registry' database
# Harbor 2.14 only needs one database — Notary was removed in v2.9
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-pg
  namespace: database
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  bootstrap:
    initdb:
      database: registry
      owner: harbor
      secret:
        name: harbor-pg-credentials
      dataChecksums: true
      localeCollate: "en_US.UTF-8"
      localeCType: "en_US.UTF-8"

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "512MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
      wal_buffers: "8MB"
      random_page_cost: "1.1"
      log_min_duration_statement: "500"

  storage:
    size: 20Gi
    storageClass: harvester

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  affinity:
    nodeSelector:
      workload-type: database
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname

  monitoring:
    enablePodMonitor: false

  backup:
    barmanObjectStore:
      destinationPath: "s3://cnpg-backups/harbor-pg"
      endpointURL: "http://minio.minio.svc.cluster.local:9000"
      s3Credentials:
        accessKeyId:
          name: cnpg-minio-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-minio-credentials
          key: ACCESS_SECRET_KEY
    retentionPolicy: "1d"
