apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-buckets
  namespace: minio
spec:
  backoffLimit: 4
  template:
    spec:
      nodeSelector:
        workload-type: database
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-root-credentials
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-root-credentials
                  key: root-password
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://minio.minio.svc.cluster.local:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD"
              mc mb --ignore-existing local/harbor
              mc mb --ignore-existing local/cnpg-backups
              mc mb --ignore-existing local/mariadb-backups
              echo "Buckets created successfully"
