apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-ca-sync
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rancher-ca-sync
  namespace: cattle-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["stv-aggregation"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rancher-ca-sync
  namespace: cattle-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rancher-ca-sync
subjects:
  - kind: ServiceAccount
    name: rancher-ca-sync
    namespace: cattle-system
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rancher-ca-sync
  namespace: cattle-system
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 60
      template:
        metadata:
          labels:
            app: rancher-ca-sync
        spec:
          serviceAccountName: rancher-ca-sync
          restartPolicy: Never
          nodeSelector:
            workload-type: general
          containers:
            - name: sync
              image: harbor.CHANGEME_DOMAIN/library/rancher-ca-sync:v0.1.0
              env:
                - name: RANCHER_URL
                  value: "https://CHANGEME_RANCHER_FQDN"
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                runAsUser: 65534
                readOnlyRootFilesystem: true
                capabilities:
                  drop: ["ALL"]
