apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-cache
  namespace: dhi-builder
  labels:
    app.kubernetes.io/name: dhi-builder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
