apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app: alloy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
  labels:
    app: alloy
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - pods
      - endpoints
      - services
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources:
      - replicasets
      - deployments
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
  labels:
    app: alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alloy
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: monitoring
