apiVersion: autoscaling.volume-autoscaler.io/v1alpha1
kind: VolumeAutoscaler
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  target:
    pvcName: uptime-kuma-data
  thresholdPercent: 80
  maxSize: 10Gi
  increasePercent: 25
  increaseMinimum: 1Gi
  pollInterval: 120s
  cooldownPeriod: 10m
