apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-ci-push
  namespace: gitlab-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-ci-push
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: ci/harbor-push
        property: username
    - secretKey: password
      remoteRef:
        key: ci/harbor-push
        property: password
